TOP = ../..
include $(TOP)/configure/CONFIG
# Do templates first so they're installed before they're needed
DIRS += templates
DIRS += bsa
DIRS += evr
DIRS += evrModule
DIRS += ioc
include $(TOP)/configure/RULES_DIRS
